name = "da-fx"
main = "src/index.ts"
compatibility_date = "2022-04-28"
routes = [{pattern = "*fixdeviantart.com/*", zone_id = "f009dd5ac46d7317252f2592cddddd3b"}]
[vars]
# The necessary secrets are:
# - DA_COOKIE - a json object containing the auth_secure, auth, and userinfo cookies
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
